import type { Locale } from "../data/locales";

export type Publication = {
  title:string;
  venue:string;
  period:string;
  authors:string;
  url:string;
  downloadUrl:string;
  abstract:string;
};

export const publications: Record<Locale, Publication[]> = {
  fa:[
    {title:"New Ephemeris of BZ Leo, V2545 Cyg and V0402 Gem",venue:"Journal of Occultation and Eclipse (JOE), No. 7",period:"2020",authors:"A. Poro, L. Shirzadi, A. Safary, S. Memarzadeh",url:"https://hal.science/hal-02501416v1",downloadUrl:"https://hal.science/hal-02501416v1",abstract:"اپمریس جدید سه سامانهٔ دوتایی گرفتی BZ Leo، V2545 Cyg و V0402 Gem ارائه می‌شود. مشاهدات با دوربین CCD و از طریق فیلتر C انجام شد. این سه سامانه از نوع W UMa برای نخستین بار بررسی شدند؛ بنابراین از پایگاه دادهٔ انجمن نجوم جمهوری چک برای استخراج داده‌های خام منحنی‌های نوری کامل و به‌دست‌آوردن زمان کمینه‌ها استفاده شد تا با اپمریس جدید، مقادیر O−C محاسبه شوند."},
    {title:"O-C Study on 545 Lunar Occultation Events of 13 Binary Stars",venue:"Journal of Occultation and Eclipse (JOE), No. 6",period:"2019",authors:"A. Poro، S. Memarzadeh و همکاران",url:"https://hal.science/hal-02306413v1",downloadUrl:"https://hal.science/hal-02306413v1",abstract:"در این مقاله، گزارش‌های اختفای ماه از سوی تیم‌های رصدی این پروژه (با نام APTO) در مقایسه با سایر مشاهدات این اجرام بررسی شده است. برای این مطالعه ۱۳ ستارهٔ دوتایی انتخاب شد و همهٔ مشاهدات پیشین این ستاره‌ها نیز گردآوری شد. در نهایت، تحلیل O−C تمامی گزارش‌ها انجام گرفت."}
  ],
  en:[
    {title:"New Ephemeris of BZ Leo, V2545 Cyg and V0402 Gem",venue:"Journal of Occultation and Eclipse (JOE), No. 7",period:"2020",authors:"A. Poro, L. Shirzadi, A. Safary, S. Memarzadeh",url:"https://hal.science/hal-02501416v1",downloadUrl:"https://hal.science/hal-02501416v1",abstract:"The new ephemerides of the three eclipsing binary systems BZ Leo, V2545 Cyg, and V0402 Gem are presented. The observations were made with a CCD through the C filter. These three W UMa systems were studied for the first time, so the Czech Astronomical Society database was used to extract raw data from the complete light curves and obtain the times of minimum, allowing O−C values to be calculated with the new ephemerides."},
    {title:"O-C Study on 545 Lunar Occultation Events of 13 Binary Stars",venue:"Journal of Occultation and Eclipse (JOE), No. 6",period:"2019",authors:"A. Poro, S. Memarzadeh and collaborators",url:"https://hal.science/hal-02306413v1",downloadUrl:"https://hal.science/hal-02306413v1",abstract:"In this article, reports of lunar occultations made by the project's observing teams (named APTO) are studied in comparison with other observations of the objects. Thirteen binary stars were selected for this study, and all previous observations of these stars were also collected. Finally, an O−C analysis of all reports was performed."}
  ],
  ar:[
    {title:"New Ephemeris of BZ Leo, V2545 Cyg and V0402 Gem",venue:"Journal of Occultation and Eclipse (JOE), No. 7",period:"2020",authors:"A. Poro, L. Shirzadi, A. Safary, S. Memarzadeh",url:"https://hal.science/hal-02501416v1",downloadUrl:"https://hal.science/hal-02501416v1",abstract:"تُعرض في هذه الدراسة العناصر المدارية الجديدة لثلاثة أنظمة ثنائية كسوفية هي BZ Leo وV2545 Cyg وV0402 Gem. أُجريت الرصدات باستخدام كاميرا CCD عبر مرشح C. وقد دُرست هذه الأنظمة الثلاثة من نوع W UMa للمرة الأولى، ولذلك استُخدمت قاعدة بيانات الجمعية الفلكية التشيكية لاستخراج البيانات الخام من منحنيات الضوء الكاملة والحصول على أزمنة الحد الأدنى، ومن ثم حساب قيم O−C باستخدام العناصر المدارية الجديدة."},
    {title:"O-C Study on 545 Lunar Occultation Events of 13 Binary Stars",venue:"Journal of Occultation and Eclipse (JOE), No. 6",period:"2019",authors:"A. Poro، S. Memarzadeh و همکاران",url:"https://hal.science/hal-02306413v1",downloadUrl:"https://hal.science/hal-02306413v1",abstract:"تتناول هذه المقالة تقارير احتجاب القمر التي أعدّتها فرق الرصد في هذا المشروع (المسمّاة APTO)، مع مقارنتها برصدات أخرى للأجرام نفسها. اختيرت 13 نجمة ثنائية لهذه الدراسة، وجُمعت أيضًا جميع الرصدات السابقة لهذه النجوم. وفي النهاية، أُجري تحليل O−C لجميع التقارير."}
  ],
  ru:[
    {title:"New Ephemeris of BZ Leo, V2545 Cyg and V0402 Gem",venue:"Journal of Occultation and Eclipse (JOE), No. 7",period:"2020",authors:"A. Poro, L. Shirzadi, A. Safary, S. Memarzadeh",url:"https://hal.science/hal-02501416v1",downloadUrl:"https://hal.science/hal-02501416v1",abstract:"В работе представлены новые эфемериды трёх затменных двойных систем BZ Leo, V2545 Cyg и V0402 Gem. Наблюдения проводились с помощью ПЗС-камеры через фильтр C. Эти три системы типа W UMa исследовались впервые, поэтому для извлечения исходных данных из полных кривых блеска и определения моментов минимумов использовалась база данных Чешского астрономического общества; на их основе были рассчитаны значения O−C по новым эфемеридам."},
    {title:"O-C Study on 545 Lunar Occultation Events of 13 Binary Stars",venue:"Journal of Occultation and Eclipse (JOE), No. 6",period:"2019",authors:"A. Poro, S. Memarzadeh и соавторы",url:"https://hal.science/hal-02306413v1",downloadUrl:"https://hal.science/hal-02306413v1",abstract:"В статье исследуются сообщения о покрытиях Луной, выполненные наблюдательными группами проекта (APTO), в сравнении с другими наблюдениями тех же объектов. Для исследования были выбраны 13 двойных звёзд, а также собраны все предыдущие наблюдения этих звёзд. В заключение был выполнен анализ O−C всех сообщений."}
  ],
  de:[
    {title:"New Ephemeris of BZ Leo, V2545 Cyg and V0402 Gem",venue:"Journal of Occultation and Eclipse (JOE), No. 7",period:"2020",authors:"A. Poro, L. Shirzadi, A. Safary, S. Memarzadeh",url:"https://hal.science/hal-02501416v1",downloadUrl:"https://hal.science/hal-02501416v1",abstract:"Die Arbeit stellt neue Ephemeriden für die drei bedeckungsveränderlichen Doppelsternsysteme BZ Leo, V2545 Cyg und V0402 Gem vor. Die Beobachtungen wurden mit einer CCD-Kamera durch den C-Filter durchgeführt. Diese drei W-U-Ma-Systeme wurden erstmals untersucht. Daher wurden aus der Datenbank der Tschechischen Astronomischen Gesellschaft Rohdaten der vollständigen Lichtkurven gewonnen und die Zeitpunkte der Minima bestimmt, um mit den neuen Ephemeriden die O−C-Werte zu berechnen."},
    {title:"O-C Study on 545 Lunar Occultation Events of 13 Binary Stars",venue:"Journal of Occultation and Eclipse (JOE), No. 6",period:"2019",authors:"A. Poro, S. Memarzadeh und Mitautoren",url:"https://hal.science/hal-02306413v1",downloadUrl:"https://hal.science/hal-02306413v1",abstract:"In diesem Beitrag werden Berichte über Mondbedeckungen der Beobachtungsteams dieses Projekts (APTO) im Vergleich mit anderen Beobachtungen derselben Objekte untersucht. Für die Studie wurden 13 Doppelsterne ausgewählt und sämtliche früheren Beobachtungen dieser Sterne zusammengetragen. Abschließend wurde eine O−C-Analyse aller Berichte durchgeführt."}
  ],
  zh:[
    {title:"New Ephemeris of BZ Leo, V2545 Cyg and V0402 Gem",venue:"Journal of Occultation and Eclipse (JOE), No. 7",period:"2020",authors:"A. Poro, L. Shirzadi, A. Safary, S. Memarzadeh",url:"https://hal.science/hal-02501416v1",downloadUrl:"https://hal.science/hal-02501416v1",abstract:"本文给出了三颗食双星系统 BZ Leo、V2545 Cyg 和 V0402 Gem 的新星历。观测使用 CCD 相机并通过 C 滤镜进行。这三套 W UMa 型系统此前尚未被研究，因此研究使用捷克天文学会数据库，从完整光变曲线中提取原始数据并获得极小值时刻，进而利用新星历计算 O−C 值。"},
    {title:"O-C Study on 545 Lunar Occultation Events of 13 Binary Stars",venue:"Journal of Occultation and Eclipse (JOE), No. 6",period:"2019",authors:"A. Poro、S. Memarzadeh 等",url:"https://hal.science/hal-02306413v1",downloadUrl:"https://hal.science/hal-02306413v1",abstract:"本文研究了该项目观测团队（APTO）报告的月掩星观测，并将其与这些天体的其他观测结果进行比较。研究选取了 13 颗双星，同时收集了这些恒星此前的全部观测资料。最后，对所有报告进行了 O−C 分析。"}
  ],
  fr:[
    {title:"New Ephemeris of BZ Leo, V2545 Cyg and V0402 Gem",venue:"Journal of Occultation and Eclipse (JOE), No. 7",period:"2020",authors:"A. Poro, L. Shirzadi, A. Safary, S. Memarzadeh",url:"https://hal.science/hal-02501416v1",downloadUrl:"https://hal.science/hal-02501416v1",abstract:"Cette étude présente de nouvelles éphémérides pour trois systèmes binaires à éclipses, BZ Leo, V2545 Cyg et V0402 Gem. Les observations ont été réalisées avec une caméra CCD à travers le filtre C. Ces trois systèmes de type W UMa ont été étudiés pour la première fois. La base de données de la Société astronomique tchèque a donc été utilisée pour extraire les données brutes des courbes de lumière complètes et déterminer les instants des minima, afin de calculer les valeurs O−C à partir des nouvelles éphémérides."},
    {title:"O-C Study on 545 Lunar Occultation Events of 13 Binary Stars",venue:"Journal of Occultation and Eclipse (JOE), No. 6",period:"2019",authors:"A. Poro, S. Memarzadeh et collaborateurs",url:"https://hal.science/hal-02306413v1",downloadUrl:"https://hal.science/hal-02306413v1",abstract:"Cet article étudie les rapports d’occultations lunaires réalisés par les équipes d’observation de ce projet (APTO), en comparaison avec d’autres observations des mêmes objets. Treize étoiles binaires ont été sélectionnées pour cette étude et toutes les observations antérieures de ces étoiles ont également été rassemblées. Enfin, une analyse O−C de l’ensemble des rapports a été réalisée."}
  ],
  es:[
    {title:"New Ephemeris of BZ Leo, V2545 Cyg and V0402 Gem",venue:"Journal of Occultation and Eclipse (JOE), No. 7",period:"2020",authors:"A. Poro, L. Shirzadi, A. Safary, S. Memarzadeh",url:"https://hal.science/hal-02501416v1",downloadUrl:"https://hal.science/hal-02501416v1",abstract:"El trabajo presenta nuevas efemérides de tres sistemas binarios eclipsantes: BZ Leo, V2545 Cyg y V0402 Gem. Las observaciones se realizaron con una cámara CCD mediante el filtro C. Estos tres sistemas de tipo W UMa se estudiaron por primera vez, por lo que se utilizó la base de datos de la Sociedad Astronómica Checa para extraer datos sin procesar de las curvas de luz completas y obtener los tiempos de los mínimos, con el fin de calcular los valores O−C mediante las nuevas efemérides."},
    {title:"O-C Study on 545 Lunar Occultation Events of 13 Binary Stars",venue:"Journal of Occultation and Eclipse (JOE), No. 6",period:"2019",authors:"A. Poro, S. Memarzadeh y colaboradores",url:"https://hal.science/hal-02306413v1",downloadUrl:"https://hal.science/hal-02306413v1",abstract:"En este artículo se estudian los informes de ocultaciones lunares realizados por los equipos de observación de este proyecto (APTO), comparándolos con otras observaciones de los mismos objetos. Se seleccionaron 13 estrellas binarias y también se recopilaron todas las observaciones anteriores de estas estrellas. Finalmente, se realizó un análisis O−C de todos los informes."}
  ]
};
