import type { Locale } from "../data/locales";

export type Publication = {
  title:string;
  venue:string;
  period:string;
  authors:string;
  url:string;
  downloadUrl:string;
  abstract:string;
};

export const publications: Record<Locale, Publication[]> = {
  fa:[
    {title:"New Ephemeris of BZ Leo, V2545 Cyg and V0402 Gem",venue:"Journal of Occultation and Eclipse (JOE), No. 7",period:"2020",authors:"A. Poro, L. Shirzadi, A. Safary, S. Memarzadeh",url:"https://hal.science/hal-02501416v1",downloadUrl:"https://hal.science/hal-02501416v1",abstract:"The new ephemeris of three eclipsing binary systems BZ Leo, V2545 Cyg, and V0402 Gem are presented. The observation was made with CCD through the C filter. These three W UMa systems studied for the first time so we used the Czech astronomical society’s database to extract raw data from the complete light curves, to obtain the time of minimums to calculate O-Cs with the new ephemeris."},
    {title:"O-C Study on 545 Lunar Occultation Events of 13 Binary Stars",venue:"Journal of Occultation and Eclipse (JOE), No. 6",period:"2019",authors:"A. Poro، S. Memarzadeh و همکاران",url:"https://hal.science/hal-02306413v1",downloadUrl:"https://hal.science/hal-02306413v1",abstract:"In this article, we have studied the reports of lunar occultations by this project observation’s teams (named APTO) in comparison with other observations of the objects. Thirteen binary stars were selected for this study. All the previous observations of these stars were also collected. Finally, an analysis of O-C of all reports were performed."}
  ],
  en:[
    {title:"New Ephemeris of BZ Leo, V2545 Cyg and V0402 Gem",venue:"Journal of Occultation and Eclipse (JOE), No. 7",period:"2020",authors:"A. Poro, L. Shirzadi, A. Safary, S. Memarzadeh",url:"https://hal.science/hal-02501416v1",downloadUrl:"https://hal.science/hal-02501416v1",abstract:"The new ephemeris of three eclipsing binary systems BZ Leo, V2545 Cyg, and V0402 Gem are presented. The observation was made with CCD through the C filter. These three W UMa systems studied for the first time so we used the Czech astronomical society’s database to extract raw data from the complete light curves, to obtain the time of minimums to calculate O-Cs with the new ephemeris."},
    {title:"O-C Study on 545 Lunar Occultation Events of 13 Binary Stars",venue:"Journal of Occultation and Eclipse (JOE), No. 6",period:"2019",authors:"A. Poro, S. Memarzadeh and collaborators",url:"https://hal.science/hal-02306413v1",downloadUrl:"https://hal.science/hal-02306413v1",abstract:"In this article, we have studied the reports of lunar occultations by this project observation’s teams (named APTO) in comparison with other observations of the objects. Thirteen binary stars were selected for this study. All the previous observations of these stars were also collected. Finally, an analysis of O-C of all reports were performed."}
  ],
  ar:[
    {title:"New Ephemeris of BZ Leo, V2545 Cyg and V0402 Gem",venue:"Journal of Occultation and Eclipse (JOE), No. 7",period:"2020",authors:"A. Poro, L. Shirzadi, A. Safary, S. Memarzadeh",url:"https://hal.science/hal-02501416v1",downloadUrl:"https://hal.science/hal-02501416v1",abstract:"The new ephemeris of three eclipsing binary systems BZ Leo, V2545 Cyg, and V0402 Gem are presented. The observation was made with CCD through the C filter. These three W UMa systems studied for the first time so we used the Czech astronomical society’s database to extract raw data from the complete light curves, to obtain the time of minimums to calculate O-Cs with the new ephemeris."},
    {title:"O-C Study on 545 Lunar Occultation Events of 13 Binary Stars",venue:"Journal of Occultation and Eclipse (JOE), No. 6",period:"2019",authors:"A. Poro، S. Memarzadeh و همکاران",url:"https://hal.science/hal-02306413v1",downloadUrl:"https://hal.science/hal-02306413v1",abstract:"In this article, we have studied the reports of lunar occultations by this project observation’s teams (named APTO) in comparison with other observations of the objects. Thirteen binary stars were selected for this study. All the previous observations of these stars were also collected. Finally, an analysis of O-C of all reports were performed."}
  ],
  ru:[
    {title:"New Ephemeris of BZ Leo, V2545 Cyg and V0402 Gem",venue:"Journal of Occultation and Eclipse (JOE), No. 7",period:"2020",authors:"A. Poro, L. Shirzadi, A. Safary, S. Memarzadeh",url:"https://hal.science/hal-02501416v1",downloadUrl:"https://hal.science/hal-02501416v1",abstract:"The new ephemeris of three eclipsing binary systems BZ Leo, V2545 Cyg, and V0402 Gem are presented. The observation was made with CCD through the C filter. These three W UMa systems studied for the first time so we used the Czech astronomical society’s database to extract raw data from the complete light curves, to obtain the time of minimums to calculate O-Cs with the new ephemeris."},
    {title:"O-C Study on 545 Lunar Occultation Events of 13 Binary Stars",venue:"Journal of Occultation and Eclipse (JOE), No. 6",period:"2019",authors:"A. Poro, S. Memarzadeh и соавторы",url:"https://hal.science/hal-02306413v1",downloadUrl:"https://hal.science/hal-02306413v1",abstract:"In this article, we have studied the reports of lunar occultations by this project observation’s teams (named APTO) in comparison with other observations of the objects. Thirteen binary stars were selected for this study. All the previous observations of these stars were also collected. Finally, an analysis of O-C of all reports were performed."}
  ],
  de:[
    {title:"New Ephemeris of BZ Leo, V2545 Cyg and V0402 Gem",venue:"Journal of Occultation and Eclipse (JOE), No. 7",period:"2020",authors:"A. Poro, L. Shirzadi, A. Safary, S. Memarzadeh",url:"https://hal.science/hal-02501416v1",downloadUrl:"https://hal.science/hal-02501416v1",abstract:"The new ephemeris of three eclipsing binary systems BZ Leo, V2545 Cyg, and V0402 Gem are presented. The observation was made with CCD through the C filter. These three W UMa systems studied for the first time so we used the Czech astronomical society’s database to extract raw data from the complete light curves, to obtain the time of minimums to calculate O-Cs with the new ephemeris."},
    {title:"O-C Study on 545 Lunar Occultation Events of 13 Binary Stars",venue:"Journal of Occultation and Eclipse (JOE), No. 6",period:"2019",authors:"A. Poro, S. Memarzadeh und Mitautoren",url:"https://hal.science/hal-02306413v1",downloadUrl:"https://hal.science/hal-02306413v1",abstract:"In this article, we have studied the reports of lunar occultations by this project observation’s teams (named APTO) in comparison with other observations of the objects. Thirteen binary stars were selected for this study. All the previous observations of these stars were also collected. Finally, an analysis of O-C of all reports were performed."}
  ],
  zh:[
    {title:"New Ephemeris of BZ Leo, V2545 Cyg and V0402 Gem",venue:"Journal of Occultation and Eclipse (JOE), No. 7",period:"2020",authors:"A. Poro, L. Shirzadi, A. Safary, S. Memarzadeh",url:"https://hal.science/hal-02501416v1",downloadUrl:"https://hal.science/hal-02501416v1",abstract:"The new ephemeris of three eclipsing binary systems BZ Leo, V2545 Cyg, and V0402 Gem are presented. The observation was made with CCD through the C filter. These three W UMa systems studied for the first time so we used the Czech astronomical society’s database to extract raw data from the complete light curves, to obtain the time of minimums to calculate O-Cs with the new ephemeris."},
    {title:"O-C Study on 545 Lunar Occultation Events of 13 Binary Stars",venue:"Journal of Occultation and Eclipse (JOE), No. 6",period:"2019",authors:"A. Poro、S. Memarzadeh 等",url:"https://hal.science/hal-02306413v1",downloadUrl:"https://hal.science/hal-02306413v1",abstract:"In this article, we have studied the reports of lunar occultations by this project observation’s teams (named APTO) in comparison with other observations of the objects. Thirteen binary stars were selected for this study. All the previous observations of these stars were also collected. Finally, an analysis of O-C of all reports were performed."}
  ],
  fr:[
    {title:"New Ephemeris of BZ Leo, V2545 Cyg and V0402 Gem",venue:"Journal of Occultation and Eclipse (JOE), No. 7",period:"2020",authors:"A. Poro, L. Shirzadi, A. Safary, S. Memarzadeh",url:"https://hal.science/hal-02501416v1",downloadUrl:"https://hal.science/hal-02501416v1",abstract:"The new ephemeris of three eclipsing binary systems BZ Leo, V2545 Cyg, and V0402 Gem are presented. The observation was made with CCD through the C filter. These three W UMa systems studied for the first time so we used the Czech astronomical society’s database to extract raw data from the complete light curves, to obtain the time of minimums to calculate O-Cs with the new ephemeris."},
    {title:"O-C Study on 545 Lunar Occultation Events of 13 Binary Stars",venue:"Journal of Occultation and Eclipse (JOE), No. 6",period:"2019",authors:"A. Poro, S. Memarzadeh et collaborateurs",url:"https://hal.science/hal-02306413v1",downloadUrl:"https://hal.science/hal-02306413v1",abstract:"In this article, we have studied the reports of lunar occultations by this project observation’s teams (named APTO) in comparison with other observations of the objects. Thirteen binary stars were selected for this study. All the previous observations of these stars were also collected. Finally, an analysis of O-C of all reports were performed."}
  ],
  es:[
    {title:"New Ephemeris of BZ Leo, V2545 Cyg and V0402 Gem",venue:"Journal of Occultation and Eclipse (JOE), No. 7",period:"2020",authors:"A. Poro, L. Shirzadi, A. Safary, S. Memarzadeh",url:"https://hal.science/hal-02501416v1",downloadUrl:"https://hal.science/hal-02501416v1",abstract:"The new ephemeris of three eclipsing binary systems BZ Leo, V2545 Cyg, and V0402 Gem are presented. The observation was made with CCD through the C filter. These three W UMa systems studied for the first time so we used the Czech astronomical society’s database to extract raw data from the complete light curves, to obtain the time of minimums to calculate O-Cs with the new ephemeris."},
    {title:"O-C Study on 545 Lunar Occultation Events of 13 Binary Stars",venue:"Journal of Occultation and Eclipse (JOE), No. 6",period:"2019",authors:"A. Poro, S. Memarzadeh y colaboradores",url:"https://hal.science/hal-02306413v1",downloadUrl:"https://hal.science/hal-02306413v1",abstract:"In this article, we have studied the reports of lunar occultations by this project observation’s teams (named APTO) in comparison with other observations of the objects. Thirteen binary stars were selected for this study. All the previous observations of these stars were also collected. Finally, an analysis of O-C of all reports were performed."}
  ]
};
